export const API_URL= 'http://localhost:3000/api'
export const PROD_API_URL = 'https://52.8.178.204/api'

export const baseballThumbnail = ''
export const tableTennisThumbnail = ''
export const basketballThumbnail = ''
export const badmintonThumbnail = ''
export const volleyballThumbnail = ''
export const tennisThumbnail = ''
export const swimmingThumbnail = ''
export const gymThumbnail = ''
