name: Deploy to ACR

on:
  push:
    branches:
      - feat/pipeline
    paths:
      - 'stadium-app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stadium-app
    env:
      IMAGE_NAME: ${{ secrets.ACR_SERVER }}/frontend
      DOCKERFILE_PATH: ./dockerfile/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate build ID
        id: tag
        run: |
          echo "::set-output name=BUILD_ID::${date +"%Y%m%d.%H%M%S"}"

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.BUILD_ID }}
          file: ${{ env.DOCKERFILE_PATH }}
            
      - name: Save container hashes
        id: acr
        run: |
            echo "$(docker inspect ${{ env.IMAGE_NAME }}:latest -f '{{ .Id }}')" >> acr.txt